# -*- coding: utf-8 -*-
"""Assign1_Q8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gfj6-N9QDIIeuGOBoz7jfRzzs2QyttyY
"""

!pip install wandb

import wandb
from assign1_q3 import train

if __name__ == '__main__':
    sweep_config = {
        'method': 'grid',
        "name": "assignement1-Sweep3",
        'metric':{
            'goal': 'maximize',
            'name': 'accuracy'
        },
        
        'parameters': {
        'epochs': {
            'values': [10]
        },
        'no_hidden_layers':{
            'values': [3]
        },
        'size_hidden_layers':{
            'values': [128]
        },
        'learning_rate':{
            'values': [0.001]
        },
        'optimizer':{
            'values': ['adam']
        },
        'batch_size':{
            'values': [128]
        },
        'activation':{
            'values': ['tanh']
        },
        'weight_initializations':{
            'values': ['random']
        },
        'weight_decay':{
            'values': [0]
        },
        'loss_function':{
            'values':['ce','sq']
        }

    }
    }
    sweep_id = wandb.sweep(sweep_config,project ='assignement1-lossfunc1')
    wandb.agent(sweep_id, function=train)