wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.25
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      4: 3.7.10
      5: 0.10.25
      8:
      - 1
      - 6
activation_function:
  desc: null
  value: relu
batch_normalization:
  desc: null
  value: true
data_aug:
  desc: null
  value: false
dropout:
  desc: null
  value: 0.2
filter_org:
  desc: null
  value: 2
k:
  desc: null
  value: 3
m:
  desc: null
  value: 32
neurons_in_dense_layer:
  desc: null
  value: 32
